(def\ (i x) x)
(def\ (k x y) x)
(def\ (ki x y) y)
(def\ (s f g) (\ (x) (f x (g x))))
(def\ (b f g) (\ (x) (f (g x))))
(def\ (c f) (\ (x y) (f y x)))
(def\ (w f) (\ (x) (f x x)))
(def\ (d f g) (\ (x y) (f x (g y))))
(def\ (bi f g) (\ (x y) (f (g x y))))
(def\ (psi f g) (\ (x y) (f (g x) (g y))))
(def\ (phi f g h) (\ (x) (g (f x) (h x))))